### ISSUE TITLE
异常了，请教什么原因？

### ISSUE THREAD

**Issue by panxw** [sinkcup/AntDemo#18]
ant auto-release -DUMENG_CHANNEL=smartisanAppStore

BUILD FAILED
D:\AntDemo\custom_rules.xml:13: The following error occurred while executing thi
s line:
D:\AntDemo\custom_rules.xml:66: Execute failed: java.io.IOException: Cannot run
program "ant" (in directory "D:\AntDemoTmp"): CreateProcess error=2, ?????????
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at java.lang.Runtime.exec(Runtime.java:617)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Jav
a13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:428)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:442)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:628)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:669)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:495)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav
a:106)

**Comment by shaunthegeek** [comment]
Windows下会出这个错误。把`ant`改成具体的文件即可，比如`C:\ant.bat`
